# Generated by Django 2.2.6 on 2020-03-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
